import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import type { LanguageDetection, LanguageKey } from "./detect.js";

const IGNORED_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "target",
  "bin",
  "obj",
  ".venv",
  "__pycache__",
  ".redqueen",
  ".idea",
  ".vscode",
  ".svelte-kit",
  ".next",
  ".nuxt",
  ".cache",
]);

const KEY_NOTES_HEADER = "## Key Notes (edit me)";

export interface CodebaseMapInput {
  projectDir: string;
  languages: LanguageDetection[];
  primary: LanguageKey;
  buildCommand: string;
  testCommand: string;
  generatedAt: string;
}

export function generateCodebaseMap(input: CodebaseMapInput): string {
  const languagesSection = renderLanguages(input.languages);
  const commandsSection = renderCommands(input.buildCommand, input.testCommand);
  const layoutSection = renderTopLevelLayout(input.projectDir);
  const entryPoints = renderEntryPoints(input.projectDir, input.primary);

  return [
    "# Codebase Map",
    "",
    `Generated by \`redqueen init\` on ${input.generatedAt}. Edit freely — this file is for`,
    "human and AI orientation. Regenerate with `redqueen init --map-only`.",
    "",
    "## Languages",
    languagesSection,
    "",
    "## Commands",
    commandsSection,
    "",
    "## Top-Level Layout",
    layoutSection,
    "",
    "## Entry Points",
    entryPoints,
    "",
    KEY_NOTES_HEADER,
    "- Describe the module structure here.",
    "- Link to architecture docs.",
    "- Note any unusual conventions the AI should know.",
    "",
  ].join("\n");
}

export function mergeRegeneratedMap(existing: string, regenerated: string): string {
  const marker = KEY_NOTES_HEADER;
  const idx = existing.indexOf(marker);
  if (idx === -1) {
    throw new Error(
      `Cannot regenerate: '${marker}' marker not found in existing map. Edit manually or run 'redqueen init --force' to recreate.`,
    );
  }
  const regenIdx = regenerated.indexOf(marker);
  if (regenIdx === -1) {
    return regenerated;
  }
  // Keep everything after the marker (inclusive) from the existing file.
  const preserved = existing.slice(idx);
  const regenHead = regenerated.slice(0, regenIdx);
  return `${regenHead}${preserved}`;
}

function renderLanguages(langs: LanguageDetection[]): string {
  if (langs.length === 0) {
    return "- (no language markers detected — fill in manually)";
  }
  return langs.map((l) => `- ${l.displayName} (${l.markerFile} detected)`).join("\n");
}

function renderCommands(build: string, test: string): string {
  const lines: string[] = [];
  lines.push(`- **Build:** \`${build.length > 0 ? build : "(not configured)"}\``);
  lines.push(`- **Test:** \`${test.length > 0 ? test : "(not configured)"}\``);
  return lines.join("\n");
}

function renderTopLevelLayout(projectDir: string): string {
  let entries: string[];
  try {
    entries = readdirSync(projectDir);
  } catch {
    return "- (unreadable)";
  }
  const lines: string[] = [];
  let shown = 0;
  const sorted = [...entries].sort();
  for (const entry of sorted) {
    if (entry.startsWith(".") && entry !== ".gitignore" && entry !== ".editorconfig") {
      continue;
    }
    if (IGNORED_DIRS.has(entry)) {
      continue;
    }
    const full = join(projectDir, entry);
    let isDir: boolean;
    try {
      isDir = statSync(full).isDirectory();
    } catch {
      continue;
    }
    if (isDir) {
      lines.push(`- \`${entry}/\``);
    } else {
      lines.push(`- \`${entry}\``);
    }
    shown++;
    if (shown >= 20) {
      break;
    }
  }
  if (lines.length === 0) {
    return "- (empty)";
  }
  return lines.join("\n");
}

function renderEntryPoints(projectDir: string, primary: LanguageKey): string {
  const found: string[] = [];
  switch (primary) {
    case "node-ts":
      addIfExists(projectDir, "src/index.ts", found);
      addIfExists(projectDir, "src/index.js", found);
      addMainField(projectDir, found);
      break;
    case "dotnet":
      addAllMatching(projectDir, (e) => e.endsWith(".sln"), found);
      break;
    case "python":
      addIfExists(projectDir, "main.py", found);
      addIfExists(projectDir, "app.py", found);
      break;
    case "go":
      addIfExists(projectDir, "main.go", found);
      break;
    case "rust":
      addIfExists(projectDir, "src/main.rs", found);
      addIfExists(projectDir, "src/lib.rs", found);
      break;
    case "ruby":
      addIfExists(projectDir, "Gemfile", found);
      break;
    case "java":
      addIfExists(projectDir, "pom.xml", found);
      addIfExists(projectDir, "build.gradle", found);
      break;
    case "blank":
      addIfExists(projectDir, "README.md", found);
      addIfExists(projectDir, "Makefile", found);
      break;
  }
  if (found.length === 0) {
    return "- (none detected)";
  }
  return found.map((p) => `- \`${p}\``).join("\n");
}

function addIfExists(projectDir: string, rel: string, out: string[]): void {
  if (existsSync(join(projectDir, rel))) {
    out.push(rel);
  }
}

function addAllMatching(
  projectDir: string,
  predicate: (entry: string) => boolean,
  out: string[],
): void {
  let entries: string[];
  try {
    entries = readdirSync(projectDir);
  } catch {
    return;
  }
  for (const e of entries.sort()) {
    if (predicate(e)) {
      out.push(e);
    }
  }
}

function addMainField(projectDir: string, out: string[]): void {
  const pkgPath = join(projectDir, "package.json");
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-boolean-literal-compare -- CLAUDE.md: avoid ! operator
  if (existsSync(pkgPath) === false) {
    return;
  }
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { main?: string };
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-boolean-literal-compare -- CLAUDE.md: avoid ! operator
    if (typeof pkg.main === "string" && pkg.main.length > 0 && out.includes(pkg.main) === false) {
      out.push(pkg.main);
    }
  } catch {
    // ignore
  }
}
