import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import type { LanguageDetection, LanguageKey } from "./detect.js";

const IGNORED_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "target",
  "bin",
  "obj",
  ".venv",
  "__pycache__",
  ".redqueen",
  ".idea",
  ".vscode",
  ".svelte-kit",
  ".next",
  ".nuxt",
  ".cache",
]);

const KEY_NOTES_HEADER = "## Key Notes (edit me)";
const PURPOSE_HEADER = "### What this repo is (edit me)";
const REPO_KEY_NOTES_HEADER = "### Key Notes (edit me)";
export const REPO_HEADING_RE = /^## Repo: (.+)$/m;

export interface CodebaseMapInput {
  projectDir: string;
  languages: LanguageDetection[];
  primary: LanguageKey;
  buildCommand: string;
  testCommand: string;
  generatedAt: string;
}

export interface RepoMapInput {
  name: string;
  path: string;
  languages: LanguageDetection[];
  primary: LanguageKey;
  buildCommand: string;
  testCommand: string;
}

export interface WorkspaceMapInput {
  rootDir: string;
  repos: RepoMapInput[];
  generatedAt: string;
}

export function isWorkspaceMap(markdown: string): boolean {
  return mapHeadings(markdown).some((heading) => REPO_HEADING_RE.test(heading.text));
}

export function readmeSummary(repoPath: string): string | null {
  let readme: string;
  try {
    readme = readFileSync(join(repoPath, "README.md"), "utf8");
  } catch {
    return null;
  }
  const paragraphs = readme.split(/\r?\n\s*\r?\n/).map((paragraph) => paragraph.trim());
  return (
    paragraphs.find((paragraph) => paragraph !== "" && paragraph.startsWith("#") === false) ?? null
  );
}

export function renderRepoSection(repo: RepoMapInput): string {
  return [
    `## Repo: ${repo.name}`,
    "",
    PURPOSE_HEADER,
    readmeSummary(repo.path) ?? "- (describe this repo — no README.md found)",
    "",
    "### Languages",
    renderLanguages(repo.languages),
    "",
    "### Commands",
    renderCommands(repo.buildCommand, repo.testCommand),
    "",
    "### Top-Level Layout",
    renderTopLevelLayout(repo.path),
    "",
    "### Entry Points",
    renderEntryPoints(repo.path, repo.primary),
    "",
    REPO_KEY_NOTES_HEADER,
    "- Describe the module structure here.",
    "- Note any unusual conventions the AI should know.",
    "",
  ].join("\n");
}

export function generateWorkspaceMap(input: WorkspaceMapInput): string {
  return [
    "# Workspace Map",
    "",
    `Generated by \`redqueen init\` on ${input.generatedAt}. One section per repo — edit the`,
    '"(edit me)" blocks freely; regenerate the rest with `redqueen init --map-only`.',
    "",
    ...input.repos.map(renderRepoSection),
  ].join("\n");
}

export function generateCodebaseMap(input: CodebaseMapInput): string {
  const languagesSection = renderLanguages(input.languages);
  const commandsSection = renderCommands(input.buildCommand, input.testCommand);
  const layoutSection = renderTopLevelLayout(input.projectDir);
  const entryPoints = renderEntryPoints(input.projectDir, input.primary);

  return [
    "# Codebase Map",
    "",
    `Generated by \`redqueen init\` on ${input.generatedAt}. Edit freely — this file is for`,
    "human and AI orientation. Regenerate with `redqueen init --map-only`.",
    "",
    "## Languages",
    languagesSection,
    "",
    "## Commands",
    commandsSection,
    "",
    "## Top-Level Layout",
    layoutSection,
    "",
    "## Entry Points",
    entryPoints,
    "",
    KEY_NOTES_HEADER,
    "- Describe the module structure here.",
    "- Link to architecture docs.",
    "- Note any unusual conventions the AI should know.",
    "",
  ].join("\n");
}

export function mergeRegeneratedMap(existing: string, regenerated: string): string {
  return isWorkspaceMap(regenerated)
    ? mergeWorkspaceMap(existing, regenerated)
    : mergeFlatMap(existing, regenerated);
}

function mergeFlatMap(existing: string, regenerated: string): string {
  const marker = KEY_NOTES_HEADER;
  const idx = existing.indexOf(marker);
  if (idx === -1) {
    throw new Error(
      `Cannot regenerate: '${marker}' marker not found in existing map. Edit manually or run 'redqueen init --force' to recreate.`,
    );
  }
  const regenIdx = regenerated.indexOf(marker);
  if (regenIdx === -1) {
    return regenerated;
  }
  // Keep everything after the marker (inclusive) from the existing file.
  const preserved = existing.slice(idx);
  const regenHead = regenerated.slice(0, regenIdx);
  return `${regenHead}${preserved}`;
}

interface IMapHeading {
  text: string;
  start: number;
  end: number;
}

// Only structural headings delimit generated sections. Fenced examples in an
// editable block may contain identical headings and must survive regeneration.
function mapHeadings(markdown: string): IMapHeading[] {
  const headings: IMapHeading[] = [];
  let fence: string | null = null;
  let start = 0;
  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.replace(/\r$/, "");
    const fenceMatch = /^ {0,3}(`{3,}|~{3,})(.*)$/.exec(line);
    const delimiter = fenceMatch?.[1];
    if (fence !== null) {
      if (
        delimiter !== undefined &&
        delimiter.startsWith(fence) &&
        fenceMatch?.[2]?.trim() === ""
      ) {
        fence = null;
      }
    } else if (delimiter !== undefined) {
      fence = delimiter;
    } else if (/^#{2,3} /.test(line)) {
      headings.push({ text: line, start, end: start + line.length });
    }
    start += rawLine.length + 1;
  }
  return headings;
}

interface IRepoSection {
  name: string;
  body: string;
  separator: string;
}

function splitRepoSections(markdown: string): { head: string; sections: IRepoSection[] } {
  const headings = mapHeadings(markdown).filter((heading) => REPO_HEADING_RE.test(heading.text));
  return {
    head: markdown.slice(0, headings[0]?.start ?? markdown.length),
    sections: headings.map((heading, index) => {
      const next = headings[index + 1];
      const body = markdown.slice(heading.start, next?.start ?? markdown.length);
      // The blank line between repo sections belongs to the generated layout,
      // so moving the last repo into the middle must not remove that separator.
      const separator =
        next !== undefined && /(?:\r?\n){2}$/.test(body)
          ? body.endsWith("\r\n")
            ? "\r\n"
            : "\n"
          : "";
      return {
        name: heading.text.slice("## Repo: ".length).trim(),
        body: body.slice(0, body.length - separator.length),
        separator,
      };
    }),
  };
}

function editBlockRange(body: string, header: string): { start: number; end: number } | null {
  const headings = mapHeadings(body);
  const index = headings.findIndex((heading) => heading.text === header);
  const heading = headings[index];
  // Key Notes is last in each repo section; appended human headings are notes,
  // including appendices carried over from the legacy flat map.
  return heading === undefined
    ? null
    : {
        start: heading.end,
        end:
          header === REPO_KEY_NOTES_HEADER
            ? body.length
            : (headings[index + 1]?.start ?? body.length),
      };
}

function replaceEditBlock(body: string, header: string, replacement: string): string {
  const range = editBlockRange(body, header);
  return range === null
    ? body
    : `${body.slice(0, range.start)}${replacement}${body.slice(range.end)}`;
}

function mergeWorkspaceMap(existing: string, regenerated: string): string {
  const old = splitRepoSections(existing);
  const regen = splitRepoSections(regenerated);
  if (old.sections.length === 0) {
    if (regen.sections.length !== 1) {
      throw new Error(
        "Cannot regenerate a flat map into multiple repos: convert to a single repo workspace map first so Key Notes keep their owner.",
      );
    }
    const marker = KEY_NOTES_HEADER;
    const heading = mapHeadings(existing).find((candidate) => candidate.text === marker);
    if (heading === undefined) {
      throw new Error(
        `Cannot regenerate: '${marker}' marker not found in existing map. Edit manually or run 'redqueen init --force' to recreate.`,
      );
    }
    return replaceEditBlock(regenerated, REPO_KEY_NOTES_HEADER, existing.slice(heading.end));
  }

  const previousSections = new Map(old.sections.map((section) => [section.name, section.body]));
  const merged = regen.sections.map((section) => {
    const previous = previousSections.get(section.name);
    if (previous === undefined) {
      return `${section.body}${section.separator}`;
    }
    let body = section.body;
    for (const header of [PURPOSE_HEADER, REPO_KEY_NOTES_HEADER]) {
      const range = editBlockRange(previous, header);
      if (range !== null) {
        body = replaceEditBlock(body, header, previous.slice(range.start, range.end));
      }
    }
    return `${body}${section.separator}`;
  });
  return `${regen.head}${merged.join("")}`;
}

function renderLanguages(langs: LanguageDetection[]): string {
  if (langs.length === 0) {
    return "- (no language markers detected — fill in manually)";
  }
  return langs.map((l) => `- ${l.displayName} (${l.markerFile} detected)`).join("\n");
}

function renderCommands(build: string, test: string): string {
  const lines: string[] = [];
  lines.push(`- **Build:** \`${build.length > 0 ? build : "(not configured)"}\``);
  lines.push(`- **Test:** \`${test.length > 0 ? test : "(not configured)"}\``);
  return lines.join("\n");
}

function renderTopLevelLayout(projectDir: string): string {
  let entries: string[];
  try {
    entries = readdirSync(projectDir);
  } catch {
    return "- (unreadable)";
  }
  const lines: string[] = [];
  let shown = 0;
  const sorted = [...entries].sort();
  for (const entry of sorted) {
    if (entry.startsWith(".") && entry !== ".gitignore" && entry !== ".editorconfig") {
      continue;
    }
    if (IGNORED_DIRS.has(entry)) {
      continue;
    }
    const full = join(projectDir, entry);
    let isDir: boolean;
    try {
      isDir = statSync(full).isDirectory();
    } catch {
      continue;
    }
    if (isDir) {
      lines.push(`- \`${entry}/\``);
    } else {
      lines.push(`- \`${entry}\``);
    }
    shown++;
    if (shown >= 20) {
      break;
    }
  }
  if (lines.length === 0) {
    return "- (empty)";
  }
  return lines.join("\n");
}

function renderEntryPoints(projectDir: string, primary: LanguageKey): string {
  const found: string[] = [];
  switch (primary) {
    case "node-ts":
      addIfExists(projectDir, "src/index.ts", found);
      addIfExists(projectDir, "src/index.js", found);
      addMainField(projectDir, found);
      break;
    case "dotnet":
      addAllMatching(projectDir, (e) => e.endsWith(".sln"), found);
      break;
    case "python":
      addIfExists(projectDir, "main.py", found);
      addIfExists(projectDir, "app.py", found);
      break;
    case "go":
      addIfExists(projectDir, "main.go", found);
      break;
    case "rust":
      addIfExists(projectDir, "src/main.rs", found);
      addIfExists(projectDir, "src/lib.rs", found);
      break;
    case "ruby":
      addIfExists(projectDir, "Gemfile", found);
      break;
    case "java":
      addIfExists(projectDir, "pom.xml", found);
      addIfExists(projectDir, "build.gradle", found);
      break;
    case "blank":
      addIfExists(projectDir, "README.md", found);
      addIfExists(projectDir, "Makefile", found);
      break;
  }
  if (found.length === 0) {
    return "- (none detected)";
  }
  return found.map((p) => `- \`${p}\``).join("\n");
}

function addIfExists(projectDir: string, rel: string, out: string[]): void {
  if (existsSync(join(projectDir, rel))) {
    out.push(rel);
  }
}

function addAllMatching(
  projectDir: string,
  predicate: (entry: string) => boolean,
  out: string[],
): void {
  let entries: string[];
  try {
    entries = readdirSync(projectDir);
  } catch {
    return;
  }
  for (const e of entries.sort()) {
    if (predicate(e)) {
      out.push(e);
    }
  }
}

function addMainField(projectDir: string, out: string[]): void {
  const pkgPath = join(projectDir, "package.json");
  if (existsSync(pkgPath) === false) {
    return;
  }
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { main?: string };
    if (typeof pkg.main === "string" && pkg.main.length > 0 && out.includes(pkg.main) === false) {
      out.push(pkg.main);
    }
  } catch {
    // ignore
  }
}
