import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  generateCodebaseMap,
  generateWorkspaceMap,
  isWorkspaceMap,
  mergeRegeneratedMap,
  readmeSummary,
  renderRepoSection,
} from "../codebase-map.js";
import type { RepoMapInput } from "../codebase-map.js";

let tmp: string;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "rq-map-"));
});
afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

function sampleInput(overrides: Partial<Parameters<typeof generateCodebaseMap>[0]> = {}) {
  return {
    projectDir: tmp,
    languages: [{ key: "node-ts" as const, displayName: "Node.js", markerFile: "package.json" }],
    primary: "node-ts" as const,
    buildCommand: "npm run build",
    testCommand: "npm test",
    generatedAt: "2026-04-23",
    ...overrides,
  };
}

function sampleRepo(name: string, overrides: Partial<RepoMapInput> = {}): RepoMapInput {
  return {
    name,
    path: join(tmp, name),
    languages: [],
    primary: "blank",
    buildCommand: "",
    testCommand: "",
    ...overrides,
  };
}

function workspaceMap(repos: RepoMapInput[]): string {
  return generateWorkspaceMap({ rootDir: tmp, repos, generatedAt: "2026-09-13" });
}

describe("generateCodebaseMap", () => {
  it("includes all required sections", () => {
    writeFileSync(join(tmp, "package.json"), '{"main":"dist/index.js"}');
    mkdirSync(join(tmp, "src"));
    const map = generateCodebaseMap(sampleInput());
    expect(map).toContain("# Codebase Map");
    expect(map).toContain("## Languages");
    expect(map).toContain("## Commands");
    expect(map).toContain("## Top-Level Layout");
    expect(map).toContain("## Entry Points");
    expect(map).toContain("## Key Notes (edit me)");
    expect(map).toContain("npm run build");
    expect(map).toContain("npm test");
  });

  it("excludes noise directories from layout", () => {
    mkdirSync(join(tmp, "node_modules"));
    mkdirSync(join(tmp, "src"));
    const map = generateCodebaseMap(sampleInput());
    expect(map).toContain("`src/`");
    expect(map).not.toContain("node_modules");
  });

  it("produces a reasonable map for an empty project", () => {
    const map = generateCodebaseMap(
      sampleInput({ languages: [], primary: "blank", buildCommand: "", testCommand: "" }),
    );
    expect(map).toContain("(no language markers");
    expect(map).toContain("(not configured)");
  });

  it("keeps the legacy flat rendering byte-for-byte", () => {
    expect(generateCodebaseMap(sampleInput())).toBe(
      [
        "# Codebase Map",
        "",
        "Generated by `redqueen init` on 2026-04-23. Edit freely — this file is for",
        "human and AI orientation. Regenerate with `redqueen init --map-only`.",
        "",
        "## Languages",
        "- Node.js (package.json detected)",
        "",
        "## Commands",
        "- **Build:** `npm run build`",
        "- **Test:** `npm test`",
        "",
        "## Top-Level Layout",
        "- (empty)",
        "",
        "## Entry Points",
        "- (none detected)",
        "",
        "## Key Notes (edit me)",
        "- Describe the module structure here.",
        "- Link to architecture docs.",
        "- Note any unusual conventions the AI should know.",
        "",
      ].join("\n"),
    );
  });
});

describe("mergeRegeneratedMap", () => {
  it("preserves Key Notes section from the existing map", () => {
    const existing = [
      "# Codebase Map",
      "",
      "## Languages",
      "- Python (pyproject.toml detected)",
      "",
      "## Key Notes (edit me)",
      "- This project uses async patterns throughout.",
      "- See ARCHITECTURE.md for module details.",
      "",
    ].join("\n");
    const regenerated = [
      "# Codebase Map",
      "",
      "## Languages",
      "- Node.js (package.json detected)",
      "",
      "## Key Notes (edit me)",
      "- Default placeholder.",
      "",
    ].join("\n");

    const merged = mergeRegeneratedMap(existing, regenerated);
    expect(merged).toContain("- Node.js (package.json detected)");
    expect(merged).toContain("- This project uses async patterns throughout.");
    expect(merged).not.toContain("Default placeholder.");
  });

  it("throws when the marker is missing", () => {
    const existing = "# Codebase Map\n\n(user deleted the marker)\n";
    const regenerated = "# Codebase Map\n\n## Key Notes (edit me)\n- x\n";
    expect(() => mergeRegeneratedMap(existing, regenerated)).toThrow(/marker not found/);
  });

  it("keeps every byte after the flat marker, including appended headings", () => {
    const tail = "## Key Notes (edit me)\r\n- Keep trailing spaces.  \r\n\r\n## Links\r\nDocs.";
    const existing = `# Codebase Map\n\nOld generated content.\n\n${tail}`;
    const regenerated = "# Codebase Map\n\nNew content.\n\n## Key Notes (edit me)\nDefault.\n";
    expect(mergeRegeneratedMap(existing, regenerated)).toBe(
      `# Codebase Map\n\nNew content.\n\n${tail}`,
    );
  });

  it("returns regenerated flat content unchanged when its marker is missing", () => {
    expect(mergeRegeneratedMap("## Key Notes (edit me)\nKeep.\n", "New content.\n")).toBe(
      "New content.\n",
    );
  });
});

describe("generateWorkspaceMap", () => {
  it("writes each repo's purpose, generated fields, and notes in input order", () => {
    mkdirSync(join(tmp, "api", "src"), { recursive: true });
    writeFileSync(join(tmp, "api", "package.json"), '{"main":"dist/index.js"}');
    writeFileSync(
      join(tmp, "api", "README.md"),
      "# API\n\nThe backend service.\nSecond line.\n\nMore.\n",
    );
    mkdirSync(join(tmp, "api", "node_modules"));
    mkdirSync(join(tmp, "web"));
    const api = sampleRepo("api", {
      languages: [{ key: "node-ts", displayName: "Node.js", markerFile: "package.json" }],
      primary: "node-ts",
      buildCommand: "npm run build",
      testCommand: "npm test",
    });
    const web = sampleRepo("web");
    const map = workspaceMap([api, web]);

    expect(map).toContain("# Workspace Map");
    expect(map).toContain("Generated by `redqueen init` on 2026-09-13.");
    expect(map).toContain("### What this repo is (edit me)\nThe backend service.\nSecond line.");
    expect(map).toContain("### Languages\n- Node.js (package.json detected)");
    expect(map).toContain("### Commands\n- **Build:** `npm run build`\n- **Test:** `npm test`");
    expect(map).toContain("### Top-Level Layout\n- `README.md`\n- `package.json`\n- `src/`");
    expect(map).toContain("### Entry Points\n- `dist/index.js`");
    expect(map).not.toContain("node_modules");
    expect(map).toContain(
      "### What this repo is (edit me)\n- (describe this repo — no README.md found)",
    );
    expect(map.match(/^### Key Notes \(edit me\)$/gm)).toHaveLength(2);
    expect(map.indexOf("## Repo: api")).toBeLessThan(map.indexOf("## Repo: web"));
    expect(map).toContain(renderRepoSection(api));
    expect(renderRepoSection(web)).toContain("### Languages\n- (no language markers detected");
    expect(renderRepoSection(web)).toContain("### Entry Points\n- (none detected)");
    expect(isWorkspaceMap(map)).toBe(true);
    expect(isWorkspaceMap(map)).toBe(true);
    expect(isWorkspaceMap("# Codebase Map\n## Key Notes (edit me)\n")).toBe(false);
    expect(isWorkspaceMap("A mention of ## Repo: api inside prose.\n")).toBe(false);
  });
});

describe("readmeSummary", () => {
  it("returns the first non-heading paragraph, preserving its line breaks", () => {
    writeFileSync(
      join(tmp, "README.md"),
      "# Title\n\n## About\n\nFirst line.\nSecond line.\n\nRest.\n",
    );
    expect(readmeSummary(tmp)).toBe("First line.\nSecond line.");
  });

  it("treats a badge paragraph as content and accepts Windows line endings", () => {
    writeFileSync(join(tmp, "README.md"), "# Title\r\n\r\n[badge](x)\r\n\r\nSummary.\r\n");
    expect(readmeSummary(tmp)).toBe("[badge](x)");
  });

  it.each(["```bash", "~~~"])(
    "skips a %s block that opens the README, blank lines included",
    (fence) => {
      writeFileSync(
        join(tmp, "README.md"),
        `# Title\n\n${fence}\nnpm install\n\nnpm start\n${fence.slice(0, 3)}\n\nReal summary.\n`,
      );
      expect(readmeSummary(tmp)).toBe("Real summary.");
    },
  );

  it.each(["## Install", "```", "~~~sh"])(
    "ends the summary at a %s line that follows it without a blank line",
    (line) => {
      writeFileSync(join(tmp, "README.md"), `# Title\n\nSummary line.\n${line}\nnpm install\n`);
      expect(readmeSummary(tmp)).toBe("Summary line.");
    },
  );

  it("returns null for missing and unreadable README files", () => {
    expect(readmeSummary(tmp)).toBeNull();
    mkdirSync(join(tmp, "README.md"));
    expect(readmeSummary(tmp)).toBeNull();
  });

  it.each(["", " \n\n", "# Title\n\n## Heading\n"])(
    "returns null when README has no paragraph: %j",
    (readme) => {
      writeFileSync(join(tmp, "README.md"), readme);
      expect(readmeSummary(tmp)).toBeNull();
    },
  );
});

describe("mergeRegeneratedMap (sectioned)", () => {
  it("preserves both editable blocks by repo while updating fields, order, and membership", () => {
    const api = sampleRepo("api", { buildCommand: "old build" });
    const web = sampleRepo("web");
    const removed = sampleRepo("removed");
    const existing = workspaceMap([api, removed, web])
      .replaceAll("- (describe this repo — no README.md found)", "Human purpose.\nSecond line.")
      .replaceAll("- Describe the module structure here.", "- Shared human note.")
      .replace("- Shared human note.", "- API-specific note.");
    const added = sampleRepo("added", { testCommand: "new test" });
    const updatedApi = { ...api, buildCommand: "new build" };
    const regenerated = workspaceMap([web, updatedApi, added]);
    const merged = mergeRegeneratedMap(existing, regenerated);
    const expectedWeb = renderRepoSection(web)
      .replace("- (describe this repo — no README.md found)", "Human purpose.\nSecond line.")
      .replace("- Describe the module structure here.", "- Shared human note.");
    const expectedApi = renderRepoSection(updatedApi)
      .replace("- (describe this repo — no README.md found)", "Human purpose.\nSecond line.")
      .replace("- Describe the module structure here.", "- API-specific note.");

    expect(merged).toBe(
      regenerated
        .replace(renderRepoSection(web), expectedWeb)
        .replace(renderRepoSection(updatedApi), expectedApi),
    );
    expect(merged).not.toContain("## Repo: removed");
    expect(merged).not.toContain("old build");
    expect(merged).toContain(renderRepoSection(added));
    expect(mergeRegeneratedMap(merged, regenerated)).toBe(merged);
  });

  it("keeps the generated header and separators byte-for-byte across repeated regeneration", () => {
    const generated = workspaceMap([sampleRepo("api"), sampleRepo("web")]);
    const merged = mergeRegeneratedMap(generated, generated);
    expect(merged).toBe(generated);
    expect(mergeRegeneratedMap(merged, generated)).toBe(generated);
  });

  it("preserves empty editable blocks and nested notes headings", () => {
    const generated = workspaceMap([sampleRepo("api")]);
    const existing = generated
      .replace("- (describe this repo — no README.md found)\n", "")
      .replace("- Describe the module structure here.", "#### Architecture\n- Human note.  ");
    expect(mergeRegeneratedMap(existing, generated)).toBe(existing);
  });

  it.each(["```md", "~~~md"])(
    "preserves headings inside %s fences without treating them as map boundaries",
    (openingFence) => {
      const generated = workspaceMap([sampleRepo("api"), sampleRepo("web")]);
      const example = [
        "Example map:",
        openingFence,
        "## Repo: sample",
        "### Languages",
        "- Example language.",
        openingFence.slice(0, 3),
        "- Note after the example.",
      ].join("\n");
      const existing = generated.replace("- Describe the module structure here.", example);
      expect(mergeRegeneratedMap(existing, generated)).toBe(existing);
      expect(isWorkspaceMap(`${openingFence}\n## Repo: sample\n${openingFence.slice(0, 3)}`)).toBe(
        false,
      );
    },
  );

  it("uses generated content for a missing editable block without losing the other block", () => {
    const generated = workspaceMap([sampleRepo("api")]);
    const existing = generated
      .replace("### What this repo is (edit me)", "### Purpose")
      .replace("- Describe the module structure here.", "- Human note.");
    expect(mergeRegeneratedMap(existing, generated)).toBe(
      generated.replace("- Describe the module structure here.", "- Human note."),
    );
  });

  it("preserves editable Windows line endings without changing generated sections", () => {
    const generated = workspaceMap([sampleRepo("api")]);
    const existing = generated.replaceAll("\n", "\r\n");
    const merged = mergeRegeneratedMap(existing, generated);
    expect(merged).toContain("### What this repo is (edit me)\r\n");
    expect(merged).toContain("### Languages\n");
    expect(merged).toContain("### Key Notes (edit me)\r\n");
    expect(mergeRegeneratedMap(merged, generated)).toBe(merged);
  });

  it("carries the entire flat Key Notes body into a single workspace repo", () => {
    const notes = "\n- Keep my note.  \n\n#### Details\nMore context.\n";
    const existing = `# Codebase Map\n\n## Key Notes (edit me)${notes}`;
    const regenerated = workspaceMap([sampleRepo("api")]);
    const merged = mergeRegeneratedMap(existing, regenerated);
    expect(merged).toBe(
      `${regenerated.slice(0, regenerated.indexOf("### Key Notes (edit me)"))}### Key Notes (edit me)${notes}`,
    );
    expect(mergeRegeneratedMap(merged, regenerated)).toBe(merged);
  });

  it("preserves legacy notes appendices through conversion and consecutive regenerations", () => {
    const notes = [
      "",
      "- Keep my note.",
      "",
      "## Links",
      "Architecture link.",
      "",
      "### Details",
      "Additional human context.",
      "",
    ].join("\n");
    const existing = `# Codebase Map\n\n## Key Notes (edit me)${notes}`;
    const regenerated = workspaceMap([sampleRepo("api")]);
    const migrated = mergeRegeneratedMap(existing, regenerated);
    const firstRegeneration = mergeRegeneratedMap(migrated, regenerated);
    const secondRegeneration = mergeRegeneratedMap(firstRegeneration, regenerated);

    expect(migrated).toContain(`### Key Notes (edit me)${notes}`);
    expect(firstRegeneration).toBe(migrated);
    expect(secondRegeneration).toBe(migrated);
  });

  it("keeps flat Key Notes when the README opens with a code block", () => {
    mkdirSync(join(tmp, "api"));
    writeFileSync(
      join(tmp, "api", "README.md"),
      "# Api\n\n```bash\nnpm install\n\nnpm start\n```\n\nThe API.\n",
    );
    const existing = "# Codebase Map\n\n## Key Notes (edit me)\n- Keep my note.\n";
    const merged = mergeRegeneratedMap(existing, workspaceMap([sampleRepo("api")]));
    expect(merged).toContain("### What this repo is (edit me)\nThe API.\n");
    expect(merged).toContain("### Key Notes (edit me)\n- Keep my note.\n");
  });

  it.each(["flat", "workspace"])(
    "refuses to drop %s notes when the generated map has no block to carry them into",
    (kind) => {
      const generated = workspaceMap([sampleRepo("api")]);
      const existing =
        kind === "flat"
          ? "# Codebase Map\n\n## Key Notes (edit me)\n- Keep my note.\n"
          : generated.replace("- Describe the module structure here.", "- Keep my note.");
      expect(() =>
        mergeRegeneratedMap(existing, generated.replace("### Key Notes (edit me)", "### Notes")),
      ).toThrow(/no '### Key Notes \(edit me\)' block/);
    },
  );

  it("refuses to guess which repo owns flat notes in a multi-repo conversion", () => {
    const existing = "# Codebase Map\n\n## Key Notes (edit me)\n- Keep my note.\n";
    expect(() =>
      mergeRegeneratedMap(existing, workspaceMap([sampleRepo("api"), sampleRepo("web")])),
    ).toThrow(/single repo/);
  });

  it("refuses to lose flat notes when their marker is missing during conversion", () => {
    expect(() =>
      mergeRegeneratedMap("# Codebase Map\nHuman notes.\n", workspaceMap([sampleRepo("api")])),
    ).toThrow(/marker not found/);
  });
});
