import type { PhaseDefinition } from "./types.js";

export const DEFAULT_PHASES: PhaseDefinition[] = [
  {
    name: "spec-writing",
    label: "Spec Writing",
    type: "automated",
    skill: "prompt-writer",
    next: "plan-review",
    onFail: "spec-awaiting-info",
    assignTo: "ai",
  },
  {
    name: "plan-review",
    label: "Plan Review",
    type: "automated",
    skill: "planning-review",
    next: "spec-review",
    onFail: "spec-feedback",
    maxIterations: 3,
    escalateTo: "spec-review",
    assignTo: "ai",
    requiresPr: false,
  },
  {
    name: "spec-review",
    label: "Spec Review",
    type: "human-gate",
    next: "coding",
    rework: "spec-feedback",
    assignTo: "human",
  },
  {
    name: "spec-feedback",
    label: "Spec Feedback",
    type: "automated",
    skill: "prompt-writer",
    next: "plan-review",
    maxIterations: 3,
    escalateTo: "blocked",
    assignTo: "ai",
    requiresPr: false,
  },
  {
    name: "spec-awaiting-info",
    label: "Awaiting Info",
    type: "human-gate",
    next: "spec-writing",
    assignTo: "human",
  },
  {
    name: "coding",
    label: "Coding",
    type: "automated",
    skill: "coder",
    next: "code-review",
    assignTo: "ai",
  },
  {
    name: "code-review",
    label: "Code Review",
    type: "automated",
    skill: "reviewer",
    next: "testing",
    onFail: "coding",
    maxIterations: 3,
    escalateTo: "human-review",
    assignTo: "ai",
  },
  {
    name: "testing",
    label: "Testing",
    type: "automated",
    skill: "tester",
    next: "human-review",
    onFail: "coding",
    assignTo: "ai",
  },
  {
    name: "human-review",
    label: "Human Review",
    type: "human-gate",
    next: "done",
    rework: "code-feedback",
    assignTo: "human",
  },
  {
    name: "code-feedback",
    label: "Code Feedback",
    type: "automated",
    skill: "comment-handler",
    next: "code-review",
    maxIterations: 3,
    escalateTo: "human-review",
    assignTo: "ai",
    requiresPr: true,
  },
  {
    name: "blocked",
    label: "Blocked",
    type: "human-gate",
    next: "coding",
    assignTo: "human",
  },
];
